name: Mirror Push
on: 
  push:
    branches-ignore:
      - "ga-ignore-**"
  pull_request:
    branches-ignore:
      - "ga-ignore-**"

env:
  MIRROR_URL: git@github.com:EpitechPGEPromo2029/B-WEB-200-BDX-2-1-epytodo-raphael.farge.git
  MIRROR_REPO: B-WEB-200-BDX-2-1-epytodo-raphael.farge

jobs:
  check_repository:
    runs-on: ubuntu-latest
    outputs:
      same_repo: ${{ steps.repo.outputs.same_repo }}
    steps:
      - name: Check repository's name
        id: repo
        run: |
          if [[ "${{ github.repository }}" == "${{ env.MIRROR_REPO }}" ]]; then
            echo "same_repo=true" >> $GITHUB_OUTPUT
          else
            echo "same_repo=false" >> $GITHUB_OUTPUT
          fi

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: check_repository
    if: ${{ needs.check_repository.outputs.same_repo == 'false' && github.event_name == 'push' && success() }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{env.MIRROR_URL}}
          ssh_private_key: ${{secrets.GIT_SSH_PRIVATE_KEY}}
